

const ADD_USER = 'ADD_USER';
const ADD_COMMENT = 'ADD_COMMENT';
const ADD_ARTICAL = 'ADD_ARTICAL';

const ADD_CAROUSEL_ITEM = 'ADD_CAROUSEL_ITEM';

export { ADD_USER, ADD_COMMENT, ADD_ARTICAL, ADD_CAROUSEL_ITEM };