

const ADD_USER = 'ADD_USER';
const ADD_COMMENT = 'ADD_COMMENT';
const ADD_ARTICAL = 'ADD_ARTICAL';

const ADD_CAROUSEL_ITEM = 'ADD_CAROUSEL_ITEM';
const ADD_ARTICAL_DETAIL = 'ADD_ARTICAL_DETAIL';

export {
  ADD_ARTICAL,
  ADD_ARTICAL_DETAIL,
  ADD_CAROUSEL_ITEM,
  ADD_COMMENT,
  ADD_USER,
};